"""initial opsmind schema

Revision ID: 1f8f0634d544
Revises: 
Create Date: 2026-09-06 03:23:21.479246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1f8f0634d544'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('incident',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'INVESTIGATING', 'DIAGNOSED', 'AWAITING_APPROVAL', 'REMEDIATING', 'VERIFYING', 'RESOLVED', 'UNRESOLVED', name='incidentstatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incident_severity'), 'incident', ['severity'], unique=False)
    op.create_index(op.f('ix_incident_status'), 'incident', ['status'], unique=False)
    op.create_index(op.f('ix_incident_title'), 'incident', ['title'], unique=False)
    op.create_table('session',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sa.Enum('LOG', 'METRIC', 'DEPLOYMENT_EVENT', 'RUNBOOK', name='evidencesource'), nullable=False),
    sa.Column('source_reference', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_incident_id'), 'evidence', ['incident_id'], unique=False)
    op.create_index(op.f('ix_evidence_occurred_at'), 'evidence', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_evidence_source'), 'evidence', ['source'], unique=False)
    op.create_table('hypothesis',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('statement', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reasoning', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('PROPOSED', 'VALIDATED', 'REJECTED', name='hypothesisstatus'), nullable=False),
    sa.Column('supporting_evidence_ids', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_incident_id'), 'hypothesis', ['incident_id'], unique=False)
    op.create_index(op.f('ix_hypothesis_status'), 'hypothesis', ['status'], unique=False)
    op.create_table('incidentevent',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.Column('event_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidentevent_event_type'), 'incidentevent', ['event_type'], unique=False)
    op.create_index(op.f('ix_incidentevent_incident_id'), 'incidentevent', ['incident_id'], unique=False)
    op.create_index(op.f('ix_incidentevent_occurred_at'), 'incidentevent', ['occurred_at'], unique=False)
    op.create_table('postmortem',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('root_cause_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timeline_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lessons_learned', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_items', sa.JSON(), nullable=True),
    sa.Column('written_by', sa.Integer(), nullable=True),
    sa.Column('written_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['written_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postmortem_incident_id'), 'postmortem', ['incident_id'], unique=True)
    op.create_table('diagnosis',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=False),
    sa.Column('probable_cause', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('impact', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('diagnosed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypothesis.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_diagnosis_incident_id'), 'diagnosis', ['incident_id'], unique=False)
    op.create_index(op.f('ix_diagnosis_is_active'), 'diagnosis', ['is_active'], unique=False)
    op.create_table('remediation',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('diagnosis_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.Enum('ROLLBACK_DEPLOYMENT', 'RESTART_SERVICE', 'SCALE_SERVICE', 'SWITCH_FEATURE_FLAG', name='remediationactiontype'), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=False),
    sa.Column('rationale', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('recommended_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['diagnosis_id'], ['diagnosis.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_remediation_action_type'), 'remediation', ['action_type'], unique=False)
    op.create_index(op.f('ix_remediation_incident_id'), 'remediation', ['incident_id'], unique=False)
    op.create_index(op.f('ix_remediation_is_selected'), 'remediation', ['is_selected'], unique=False)
    op.create_index(op.f('ix_remediation_risk_level'), 'remediation', ['risk_level'], unique=False)
    op.create_table('actionexecution',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('remediation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'SIMULATED', name='executionstatus'), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['remediation_id'], ['remediation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actionexecution_incident_id'), 'actionexecution', ['incident_id'], unique=False)
    op.create_index(op.f('ix_actionexecution_status'), 'actionexecution', ['status'], unique=False)
    op.create_table('approval',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('remediation_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'NOT_REQUIRED', name='approvalstatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['user.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.ForeignKeyConstraint(['remediation_id'], ['remediation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_incident_id'), 'approval', ['incident_id'], unique=False)
    op.create_index(op.f('ix_approval_status'), 'approval', ['status'], unique=False)
    op.create_table('verification',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('incident_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action_execution_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=False),
    sa.Column('recovered', sa.Boolean(), nullable=True),
    sa.Column('evidence_after_ids', sa.JSON(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['action_execution_id'], ['actionexecution.id'], ),
    sa.ForeignKeyConstraint(['incident_id'], ['incident.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_incident_id'), 'verification', ['incident_id'], unique=False)
    op.create_index(op.f('ix_verification_recovered'), 'verification', ['recovered'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_recovered'), table_name='verification')
    op.drop_index(op.f('ix_verification_incident_id'), table_name='verification')
    op.drop_table('verification')
    op.drop_index(op.f('ix_approval_status'), table_name='approval')
    op.drop_index(op.f('ix_approval_incident_id'), table_name='approval')
    op.drop_table('approval')
    op.drop_index(op.f('ix_actionexecution_status'), table_name='actionexecution')
    op.drop_index(op.f('ix_actionexecution_incident_id'), table_name='actionexecution')
    op.drop_table('actionexecution')
    op.drop_index(op.f('ix_remediation_risk_level'), table_name='remediation')
    op.drop_index(op.f('ix_remediation_is_selected'), table_name='remediation')
    op.drop_index(op.f('ix_remediation_incident_id'), table_name='remediation')
    op.drop_index(op.f('ix_remediation_action_type'), table_name='remediation')
    op.drop_table('remediation')
    op.drop_index(op.f('ix_diagnosis_is_active'), table_name='diagnosis')
    op.drop_index(op.f('ix_diagnosis_incident_id'), table_name='diagnosis')
    op.drop_table('diagnosis')
    op.drop_index(op.f('ix_postmortem_incident_id'), table_name='postmortem')
    op.drop_table('postmortem')
    op.drop_index(op.f('ix_incidentevent_occurred_at'), table_name='incidentevent')
    op.drop_index(op.f('ix_incidentevent_incident_id'), table_name='incidentevent')
    op.drop_index(op.f('ix_incidentevent_event_type'), table_name='incidentevent')
    op.drop_table('incidentevent')
    op.drop_index(op.f('ix_hypothesis_status'), table_name='hypothesis')
    op.drop_index(op.f('ix_hypothesis_incident_id'), table_name='hypothesis')
    op.drop_table('hypothesis')
    op.drop_index(op.f('ix_evidence_source'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_occurred_at'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_incident_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_table('session')
    op.drop_index(op.f('ix_incident_title'), table_name='incident')
    op.drop_index(op.f('ix_incident_status'), table_name='incident')
    op.drop_index(op.f('ix_incident_severity'), table_name='incident')
    op.drop_table('incident')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
    # PostgreSQL ENUM types are not dropped automatically when the tables
    # that use them are dropped - Alembic's autogenerate does not add these
    # statements on its own, so they are added by hand, in the reverse order
    # tables were dropped above.
    sa.Enum(name='executionstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='approvalstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='risklevel').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='remediationactiontype').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='hypothesisstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='evidencesource').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='incidentstatus').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='severity').drop(op.get_bind(), checkfirst=True)