"""Hypothesis generation node for the incident investigation graph."""

from typing import Optional, Protocol

from langchain_core.messages import HumanMessage, SystemMessage
from pydantic import BaseModel, Field

from app.core.config import settings
from app.investigation.schemas import (
    EvidenceCitation,
    HypothesisCandidate,
    InvestigationState,
    TimelineEntry,
)
from app.services.llm import LLMRegistry

_SYSTEM_PROMPT = """You are investigating a production incident for the service "{service}".

You will be given a numbered list of timeline events (logs and deployments)
observed during the incident. Propose up to {max_hypotheses} candidate root
causes.

Rules, followed strictly:
- Every hypothesis MUST reference at least one event by its number in
  supporting_evidence_indices. Never propose a hypothesis with no
  supporting evidence.
- Only reference event numbers that actually appear in the list you were
  given. Never invent or reference a number outside that list.
- confidence must be between 0.0 and 1.0.
- Do not restate the raw event text as your "statement" - explain what you
  believe caused the incident, using the events as evidence for that claim.
"""


class _RawHypothesis(BaseModel):
    """Structured LLM output for a single candidate hypothesis, pre-resolution.

    supporting_evidence_indices are 1-based positions into the numbered
    timeline list the LLM was shown, not database IDs or EvidenceCitation
    objects - those are resolved afterward from real data, never trusted
    as text generated by the model.
    """

    statement: str
    reasoning: str = ""
    confidence: float = Field(ge=0.0, le=1.0)
    supporting_evidence_indices: list[int] = Field(default_factory=list)


class _HypothesisGenerationOutput(BaseModel):
    """Structured LLM output: the full set of candidate hypotheses proposed."""

    hypotheses: list[_RawHypothesis] = Field(default_factory=list)


class StructuredLLM(Protocol):
    """The minimal interface this node actually depends on.

    Deliberately not BaseChatModel - only ainvoke(messages) ->
    _HypothesisGenerationOutput is required, which makes this node
    trivially testable with a plain stub object, no real LLM or API key
    needed for tests.
    """

    async def ainvoke(self, messages: list) -> _HypothesisGenerationOutput: ...


class HypothesisGeneratorNode:
    """LangGraph node that proposes candidate root-cause hypotheses from the timeline.

    Every hypothesis returned is guaranteed to reference at least one real
    timeline entry - the LLM references entries by index, and any
    hypothesis whose indices don't all resolve to real entries after the
    call is dropped rather than kept with fabricated grounding.
    """

    def __init__(
        self,
        structured_llm: Optional[StructuredLLM] = None,
        max_hypotheses: int = 3,
    ):
        """Initialize the node.

        Args:
            structured_llm: A structured-output-wrapped LLM implementing
                StructuredLLM. Defaults to the $0 Groq default model from
                LLMRegistry, wrapped via with_structured_output.
            max_hypotheses: Maximum number of hypotheses to request from
                the LLM per call.
        """
        self._structured_llm = structured_llm or LLMRegistry.get(settings.DEFAULT_LLM_MODEL).with_structured_output(
            _HypothesisGenerationOutput
        )
        self._max_hypotheses = max_hypotheses

    @staticmethod
    def _citation_source(entry: TimelineEntry) -> str:
        """Derive a short source label from a timeline entry's event_type."""
        if entry.event_type.startswith("log_"):
            return "log"
        return entry.event_type

    def _build_prompt(self, state: InvestigationState, numbered_evidence: list[TimelineEntry]) -> list:
        """Build the system/human messages sent to the LLM."""
        system = SystemMessage(
            content=_SYSTEM_PROMPT.format(service=state.service, max_hypotheses=self._max_hypotheses)
        )
        evidence_lines = [
            f"{i}. [{entry.timestamp.strftime('%H:%M:%S')}] ({entry.event_type}) {entry.description}"
            for i, entry in enumerate(numbered_evidence, start=1)
        ]
        human = HumanMessage(content="Timeline events:\n" + "\n".join(evidence_lines))
        return [system, human]

    def _resolve_hypotheses(
        self,
        raw_output: _HypothesisGenerationOutput,
        numbered_evidence: list[TimelineEntry],
    ) -> list[HypothesisCandidate]:
        """Turn raw LLM output into HypothesisCandidate objects grounded in real evidence.

        Any raw hypothesis referencing an index outside the numbered list
        it was given is dropped entirely - this is the enforcement point
        for evidence-grounding, not just a prompt instruction.
        """
        resolved: list[HypothesisCandidate] = []
        for raw in raw_output.hypotheses:
            citations: list[EvidenceCitation] = []
            valid = True
            for index in raw.supporting_evidence_indices:
                if not (1 <= index <= len(numbered_evidence)):
                    valid = False
                    break
                entry = numbered_evidence[index - 1]
                citations.append(
                    EvidenceCitation(
                        source=self._citation_source(entry),
                        content=entry.description,
                        timestamp=entry.timestamp,
                    )
                )
            if not valid or not citations:
                continue
            resolved.append(
                HypothesisCandidate(
                    statement=raw.statement,
                    reasoning=raw.reasoning,
                    confidence=raw.confidence,
                    supporting_evidence=citations,
                )
            )
        return resolved

    async def __call__(self, state: InvestigationState) -> dict:
        """Generate candidate hypotheses from the investigation's timeline.

        Args:
            state: Current investigation state. Must have evidence already
                populated by the evidence_collector node.

        Returns:
            dict: Partial state update setting hypotheses. Empty list if
            there is no timeline to reason about (no LLM call is made in
            that case, to avoid spending a free-tier request on nothing).

        Raises:
            ValueError: If evidence has not been collected yet.
        """
        if state.evidence is None:
            raise ValueError(
                "HypothesisGeneratorNode requires state.evidence to be set. "
                "Run EvidenceCollectorNode earlier in the graph first."
            )

        numbered_evidence = state.timeline
        if not numbered_evidence:
            return {"hypotheses": []}

        messages = self._build_prompt(state, numbered_evidence)
        raw_output = await self._structured_llm.ainvoke(messages)
        hypotheses = self._resolve_hypotheses(raw_output, numbered_evidence)

        return {"hypotheses": hypotheses}

    